// Player database for games - market values in millions of euros
export interface GamePlayer {
  id: number;
  name: string;
  club: string;
  nationality: string;
  position: string;
  marketValue: number; // in millions
  photo?: string;
}

export const PLAYERS: GamePlayer[] = [
  { id: 1, name: "Kylian Mbappé", club: "Real Madrid", nationality: "France", position: "Forward", marketValue: 180, photo: "https://media.api-sports.io/football/players/278.png" },
  { id: 2, name: "Erling Haaland", club: "Manchester City", nationality: "Norway", position: "Forward", marketValue: 200, photo: "https://media.api-sports.io/football/players/1100.png" },
  { id: 3, name: "Vinicius Jr", club: "Real Madrid", nationality: "Brazil", position: "Forward", marketValue: 140, photo: "https://media.api-sports.io/football/players/762.png" },
  { id: 4, name: "Jude Bellingham", club: "Real Madrid", nationality: "England", position: "Midfielder", marketValue: 130, photo: "https://media.api-sports.io/football/players/129718.png" },
  { id: 5, name: "Bukayo Saka", club: "Arsenal", nationality: "England", position: "Forward", marketValue: 110, photo: "https://media.api-sports.io/football/players/1460.png" },
  { id: 6, name: "Phil Foden", club: "Manchester City", nationality: "England", position: "Midfielder", marketValue: 70, photo: "https://media.api-sports.io/football/players/631.png" },
  { id: 7, name: "Florian Wirtz", club: "Liverpool", nationality: "Germany", position: "Midfielder", marketValue: 100, photo: "https://media.api-sports.io/football/players/203224.png" },
  { id: 8, name: "Lamine Yamal", club: "Barcelona", nationality: "Spain", position: "Forward", marketValue: 200, photo: "https://media.api-sports.io/football/players/386828.png" },
  { id: 9, name: "Rodri", club: "Manchester City", nationality: "Spain", position: "Midfielder", marketValue: 50, photo: "https://media.api-sports.io/football/players/44.png" },
  { id: 10, name: "Pedri", club: "Barcelona", nationality: "Spain", position: "Midfielder", marketValue: 150, photo: "https://media.api-sports.io/football/players/133609.png" },
  { id: 11, name: "Jamal Musiala", club: "Bayern Munich", nationality: "Germany", position: "Forward", marketValue: 100, photo: "https://media.api-sports.io/football/players/181812.png" },
  { id: 12, name: "Mohamed Salah", club: "Liverpool", nationality: "Egypt", position: "Forward", marketValue: 40, photo: "https://media.api-sports.io/football/players/306.png" },
  { id: 13, name: "Bruno Fernandes", club: "Manchester United", nationality: "Portugal", position: "Midfielder", marketValue: 35, photo: "https://media.api-sports.io/football/players/1485.png" },
  { id: 14, name: "Martin Ødegaard", club: "Arsenal", nationality: "Norway", position: "Midfielder", marketValue: 65, photo: "https://media.api-sports.io/football/players/2295.png" },
  { id: 15, name: "Declan Rice", club: "Arsenal", nationality: "England", position: "Midfielder", marketValue: 120, photo: "https://media.api-sports.io/football/players/2937.png" },
  { id: 16, name: "Harry Kane", club: "Bayern Munich", nationality: "England", position: "Forward", marketValue: 60, photo: "https://media.api-sports.io/football/players/184.png" },
  { id: 17, name: "Lautaro Martínez", club: "Inter", nationality: "Argentina", position: "Forward", marketValue: 85, photo: "https://media.api-sports.io/football/players/907.png" },
  { id: 18, name: "Gavi", club: "Barcelona", nationality: "Spain", position: "Midfielder", marketValue: 30, photo: "https://media.api-sports.io/football/players/296667.png" },
  { id: 19, name: "Federico Valverde", club: "Real Madrid", nationality: "Uruguay", position: "Midfielder", marketValue: 90, photo: "https://media.api-sports.io/football/players/12005.png" },
  { id: 20, name: "Khvicha Kvaratskhelia", club: "PSG", nationality: "Georgia", position: "Forward", marketValue: 140, photo: "https://media.api-sports.io/football/players/483.png" },
  { id: 21, name: "Alejandro Garnacho", club: "Manchester United", nationality: "Argentina", position: "Forward", marketValue: 35, photo: "https://media.api-sports.io/football/players/284324.png" },
  { id: 22, name: "Lionel Messi", club: "Inter Miami", nationality: "Argentina", position: "Forward", marketValue: 15, photo: "https://media.api-sports.io/football/players/154.png" },
  { id: 23, name: "Cristiano Ronaldo", club: "Al-Nassr", nationality: "Portugal", position: "Forward", marketValue: 10, photo: "https://media.api-sports.io/football/players/874.png" },
  { id: 24, name: "Neymar Jr", club: "Santos", nationality: "Brazil", position: "Forward", marketValue: 8, photo: "https://media.api-sports.io/football/players/276.png" },
  { id: 25, name: "Robert Lewandowski", club: "Barcelona", nationality: "Poland", position: "Forward", marketValue: 20, photo: "https://media.api-sports.io/football/players/521.png" },
  { id: 26, name: "Kevin De Bruyne", club: "Manchester City", nationality: "Belgium", position: "Midfielder", marketValue: 35, photo: "https://media.api-sports.io/football/players/627.png" },
  { id: 27, name: "Son Heung-min", club: "Tottenham", nationality: "South Korea", position: "Forward", marketValue: 30, photo: "https://media.api-sports.io/football/players/186.png" },
  { id: 28, name: "Virgil van Dijk", club: "Liverpool", nationality: "Netherlands", position: "Defender", marketValue: 30 , photo: "https://media.api-sports.io/football/players/647.png" },
  { id: 29, name: "Thibaut Courtois", club: "Real Madrid", nationality: "Belgium", position: "Goalkeeper", marketValue: 20 , photo: "https://media.api-sports.io/football/players/730.png" },
  { id: 30, name: "Alisson", club: "Liverpool", nationality: "Brazil", position: "Goalkeeper", marketValue: 20 , photo: "https://media.api-sports.io/football/players/280.png" },
  { id: 31, name: "Dani Olmo", club: "Barcelona", nationality: "Spain", position: "Midfielder", marketValue: 60 , photo: "https://media.api-sports.io/football/players/19544.png" },
  { id: 32, name: "William Saliba", club: "Arsenal", nationality: "France", position: "Defender", marketValue: 100 , photo: "https://media.api-sports.io/football/players/22090.png" },
  { id: 33, name: "Nico Williams", club: "Athletic Club", nationality: "Spain", position: "Forward", marketValue: 40 , photo: "https://media.api-sports.io/football/players/183799.png" },
  { id: 34, name: "Cole Palmer", club: "Chelsea", nationality: "England", position: "Forward", marketValue: 100 , photo: "https://media.api-sports.io/football/players/152982.png" },
  { id: 35, name: "Bernardo Silva", club: "Manchester City", nationality: "Portugal", position: "Midfielder", marketValue: 40 , photo: "https://media.api-sports.io/football/players/633.png" },
  { id: 36, name: "Raphinha", club: "Barcelona", nationality: "Brazil", position: "Forward", marketValue: 70 , photo: "https://media.api-sports.io/football/players/6641.png" },
  { id: 37, name: "Antonio Rüdiger", club: "Real Madrid", nationality: "Germany", position: "Defender", marketValue: 25 , photo: "https://media.api-sports.io/football/players/2285.png" },
  { id: 38, name: "Achraf Hakimi", club: "PSG", nationality: "Morocco", position: "Defender", marketValue: 80 , photo: "https://media.api-sports.io/football/players/2430.png" },
  { id: 39, name: "Trent Alexander-Arnold", club: "Liverpool", nationality: "England", position: "Defender", marketValue: 60 , photo: "https://media.api-sports.io/football/players/283.png" },
  { id: 40, name: "Marc-André ter Stegen", club: "Barcelona", nationality: "Germany", position: "Goalkeeper", marketValue: 3 , photo: "https://media.api-sports.io/football/players/162.png" },
  { id: 41, name: "Julián Álvarez", club: "Atlético Madrid", nationality: "Argentina", position: "Forward", marketValue: 100 , photo: "https://media.api-sports.io/football/players/46973.png" },
  { id: 42, name: "Aurélien Tchouaméni", club: "Real Madrid", nationality: "France", position: "Midfielder", marketValue: 70 , photo: "https://media.api-sports.io/football/players/36832.png" },
  { id: 43, name: "Victor Osimhen", club: "Napoli", nationality: "Nigeria", position: "Forward", marketValue: 75 , photo: "https://media.api-sports.io/football/players/3246.png" },
  { id: 44, name: "Alexander Isak", club: "Newcastle", nationality: "Sweden", position: "Forward", marketValue: 85 , photo: "https://media.api-sports.io/football/players/2917.png" },
  { id: 45, name: "Dani Carvajal", club: "Real Madrid", nationality: "Spain", position: "Defender", marketValue: 20 , photo: "https://media.api-sports.io/football/players/726.png" },
  // More Defenders
  { id: 46, name: "Rúben Dias", club: "Manchester City", nationality: "Portugal", position: "Defender", marketValue: 55 , photo: "https://media.api-sports.io/football/players/567.png" },
  { id: 47, name: "João Cancelo", club: "Barcelona", nationality: "Portugal", position: "Defender", marketValue: 30 , photo: "https://media.api-sports.io/football/players/641.png" },
  { id: 48, name: "Theo Hernández", club: "AC Milan", nationality: "France", position: "Defender", marketValue: 35 , photo: "https://media.api-sports.io/football/players/15799.png" },
  { id: 49, name: "Jules Koundé", club: "Barcelona", nationality: "France", position: "Defender", marketValue: 60 , photo: "https://media.api-sports.io/football/players/16124.png" },
  { id: 50, name: "Marquinhos", club: "PSG", nationality: "Brazil", position: "Defender", marketValue: 30 , photo: "https://media.api-sports.io/football/players/1783.png" },
  { id: 51, name: "Eder Militão", club: "Real Madrid", nationality: "Brazil", position: "Defender", marketValue: 40 , photo: "https://media.api-sports.io/football/players/372.png" },
  { id: 52, name: "Josko Gvardiol", club: "Manchester City", nationality: "Croatia", position: "Defender", marketValue: 70 , photo: "https://media.api-sports.io/football/players/153079.png" },
  { id: 53, name: "Ronald Araújo", club: "Barcelona", nationality: "Uruguay", position: "Defender", marketValue: 40 , photo: "https://media.api-sports.io/football/players/101814.png" },
  { id: 54, name: "Dayot Upamecano", club: "Bayern Munich", nationality: "France", position: "Defender", marketValue: 70 , photo: "https://media.api-sports.io/football/players/1149.png" },
  { id: 55, name: "Lisandro Martínez", club: "Manchester United", nationality: "Argentina", position: "Defender", marketValue: 40 , photo: "https://media.api-sports.io/football/players/47620.png" },
  { id: 56, name: "Andrew Robertson", club: "Liverpool", nationality: "Scotland", position: "Defender", marketValue: 20 , photo: "https://media.api-sports.io/football/players/289.png" },
  { id: 57, name: "Ben White", club: "Arsenal", nationality: "England", position: "Defender", marketValue: 45 , photo: "https://media.api-sports.io/football/players/18885.png" },
  { id: 58, name: "Alessandro Bastoni", club: "Inter", nationality: "Italy", position: "Defender", marketValue: 65 , photo: "https://media.api-sports.io/football/players/31009.png" },
  { id: 59, name: "Alphonso Davies", club: "Real Madrid", nationality: "Canada", position: "Defender", marketValue: 40 , photo: "https://media.api-sports.io/football/players/15799.png" },
  { id: 60, name: "Pau Cubarsí", club: "Barcelona", nationality: "Spain", position: "Defender", marketValue: 80 , photo: "https://media.api-sports.io/football/players/406500.png" },
  // More Goalkeepers
  { id: 61, name: "Ederson", club: "Manchester City", nationality: "Brazil", position: "Goalkeeper", marketValue: 30 , photo: "https://media.api-sports.io/football/players/19599.png" },
  { id: 62, name: "Gianluigi Donnarumma", club: "PSG", nationality: "Italy", position: "Goalkeeper", marketValue: 45 , photo: "https://media.api-sports.io/football/players/1622.png" },
  { id: 63, name: "Jan Oblak", club: "Atlético Madrid", nationality: "Slovenia", position: "Goalkeeper", marketValue: 20 , photo: "https://media.api-sports.io/football/players/29.png" },
  { id: 64, name: "André Onana", club: "Manchester United", nationality: "Cameroon", position: "Goalkeeper", marketValue: 30 , photo: "https://media.api-sports.io/football/players/526.png" },
  { id: 65, name: "Diogo Costa", club: "Porto", nationality: "Portugal", position: "Goalkeeper", marketValue: 40 , photo: "https://media.api-sports.io/football/players/47392.png" },
  { id: 66, name: "Mike Maignan", club: "AC Milan", nationality: "France", position: "Goalkeeper", marketValue: 35 , photo: "https://media.api-sports.io/football/players/22221.png" },
  { id: 67, name: "Emiliano Martínez", club: "Aston Villa", nationality: "Argentina", position: "Goalkeeper", marketValue: 30 , photo: "https://media.api-sports.io/football/players/19599.png" },
  // More Midfielders
  { id: 68, name: "Enzo Fernández", club: "Chelsea", nationality: "Argentina", position: "Midfielder", marketValue: 90 , photo: "https://media.api-sports.io/football/players/5996.png" },
  { id: 69, name: "Alexis Mac Allister", club: "Liverpool", nationality: "Argentina", position: "Midfielder", marketValue: 70 , photo: "https://media.api-sports.io/football/players/6716.png" },
  { id: 70, name: "Luka Modric", club: "Real Madrid", nationality: "Croatia", position: "Midfielder", marketValue: 3.5 , photo: "https://media.api-sports.io/football/players/753.png" },
  { id: 71, name: "Eduardo Camavinga", club: "Real Madrid", nationality: "France", position: "Midfielder", marketValue: 50 , photo: "https://media.api-sports.io/football/players/2207.png" },
  { id: 72, name: "Vitinha", club: "PSG", nationality: "Portugal", position: "Midfielder", marketValue: 140 , photo: "https://media.api-sports.io/football/players/129090.png" },
  { id: 73, name: "Sandro Tonali", club: "Newcastle", nationality: "Italy", position: "Midfielder", marketValue: 80 , photo: "https://media.api-sports.io/football/players/47349.png" },
  // More Forwards
  { id: 74, name: "Darwin Núñez", club: "Liverpool", nationality: "Uruguay", position: "Forward", marketValue: 35 , photo: "https://media.api-sports.io/football/players/47624.png" },
  { id: 75, name: "Marcus Rashford", club: "Manchester United", nationality: "England", position: "Forward", marketValue: 40 , photo: "https://media.api-sports.io/football/players/909.png" },
  { id: 76, name: "Leroy Sané", club: "Bayern Munich", nationality: "Germany", position: "Forward", marketValue: 30 , photo: "https://media.api-sports.io/football/players/1263.png" },
  { id: 77, name: "Antoine Griezmann", club: "Atlético Madrid", nationality: "France", position: "Forward", marketValue: 20 , photo: "https://media.api-sports.io/football/players/1198.png" },
  { id: 78, name: "Paulo Dybala", club: "AS Roma", nationality: "Argentina", position: "Forward", marketValue: 15 , photo: "https://media.api-sports.io/football/players/1880.png" },
  { id: 79, name: "Randal Kolo Muani", club: "PSG", nationality: "France", position: "Forward", marketValue: 30 , photo: "https://media.api-sports.io/football/players/10187.png" },
  { id: 80, name: "Jamal Musiala", club: "Bayern Munich", nationality: "Germany", position: "Forward", marketValue: 100 , photo: "https://media.api-sports.io/football/players/181812.png" },
  { id: 81, name: "Michael Olise", club: "Bayern Munich", nationality: "France", position: "Forward", marketValue: 150, photo: "https://media.api-sports.io/football/players/19617.png" },
  { id: 82, name: "Moisés Caicedo", club: "Chelsea", nationality: "Ecuador", position: "Midfielder", marketValue: 100, photo: "https://media.api-sports.io/football/players/116117.png" },
  { id: 83, name: "Fermín López", club: "Barcelona", nationality: "Spain", position: "Midfielder", marketValue: 100, photo: "https://media.api-sports.io/football/players/340626.png" },
  { id: 84, name: "Dominik Szoboszlai", club: "Liverpool", nationality: "Hungary", position: "Midfielder", marketValue: 100, photo: "https://media.api-sports.io/football/players/1096.png" },
  { id: 85, name: "Ousmane Dembélé", club: "PSG", nationality: "France", position: "Forward", marketValue: 100, photo: "https://media.api-sports.io/football/players/153.png" },
  { id: 86, name: "Arda Güler", club: "Real Madrid", nationality: "Turkey", position: "Midfielder", marketValue: 90, photo: "https://media.api-sports.io/football/players/291964.png" },
  { id: 87, name: "Morgan Rogers", club: "Aston Villa", nationality: "England", position: "Midfielder", marketValue: 90, photo: "https://media.api-sports.io/football/players/19170.png" },
  { id: 88, name: "Warren Zaïre-Emery", club: "PSG", nationality: "France", position: "Midfielder", marketValue: 80, photo: "https://media.api-sports.io/football/players/336657.png" },
  { id: 89, name: "Ryan Gravenberch", club: "Liverpool", nationality: "Netherlands", position: "Midfielder", marketValue: 80, photo: "https://media.api-sports.io/football/players/542.png" },
  { id: 90, name: "Benjamin Sesko", club: "RB Leipzig", nationality: "Slovenia", position: "Forward", marketValue: 75, photo: "https://media.api-sports.io/football/players/115589.png" },
  { id: 91, name: "Jérémy Doku", club: "Manchester City", nationality: "Belgium", position: "Forward", marketValue: 75, photo: "https://media.api-sports.io/football/players/1422.png" },
  { id: 92, name: "Martín Zubimendi", club: "Real Sociedad", nationality: "Spain", position: "Midfielder", marketValue: 75, photo: "https://media.api-sports.io/football/players/47315.png" },
  { id: 93, name: "Kobbie Mainoo", club: "Manchester United", nationality: "England", position: "Midfielder", marketValue: 70, photo: "https://media.api-sports.io/football/players/284322.png" },
  { id: 94, name: "Bradley Barcola", club: "PSG", nationality: "France", position: "Forward", marketValue: 70, photo: "https://media.api-sports.io/football/players/161904.png" },
  { id: 95, name: "Bruno Guimarães", club: "Newcastle", nationality: "Brazil", position: "Midfielder", marketValue: 70, photo: "https://media.api-sports.io/football/players/10135.png" },
  { id: 96, name: "Luis Díaz", club: "Liverpool", nationality: "Colombia", position: "Forward", marketValue: 70, photo: "https://media.api-sports.io/football/players/2489.png" },
  { id: 97, name: "Jurriën Timber", club: "Arsenal", nationality: "Netherlands", position: "Defender", marketValue: 70, photo: "https://media.api-sports.io/football/players/38746.png" },
  { id: 98, name: "Marc Guéhi", club: "Crystal Palace", nationality: "England", position: "Defender", marketValue: 70, photo: "https://media.api-sports.io/football/players/67971.png" },
  { id: 99, name: "Anthony Gordon", club: "Newcastle", nationality: "England", position: "Forward", marketValue: 65, photo: "https://media.api-sports.io/football/players/138787.png" },
  { id: 100, name: "Viktor Gyökeres", club: "Sporting CP", nationality: "Sweden", position: "Forward", marketValue: 65, photo: "https://media.api-sports.io/football/players/18979.png" },
  { id: 101, name: "Nicolò Barella", club: "Inter", nationality: "Italy", position: "Midfielder", marketValue: 50, photo: "https://media.api-sports.io/football/players/30558.png" },
  { id: 102, name: "Marcus Thuram", club: "Inter", nationality: "France", position: "Forward", marketValue: 50, photo: "https://media.api-sports.io/football/players/21509.png" },
  { id: 103, name: "Rafael Leão", club: "AC Milan", nationality: "Portugal", position: "Forward", marketValue: 50, photo: "https://media.api-sports.io/football/players/22236.png" },
  { id: 104, name: "Federico Dimarco", club: "Inter", nationality: "Italy", position: "Defender", marketValue: 50, photo: "https://media.api-sports.io/football/players/31010.png" },
  { id: 105, name: "Xavi Simons", club: "PSG", nationality: "Netherlands", position: "Forward", marketValue: 40, photo: "https://media.api-sports.io/football/players/162016.png" },
  { id: 106, name: "Rodrygo", club: "Real Madrid", nationality: "Brazil", position: "Forward", marketValue: 45, photo: "https://media.api-sports.io/football/players/10009.png" },
  { id: 107, name: "Pau Cubarsí", club: "Barcelona", nationality: "Spain", position: "Defender", marketValue: 80, photo: "https://media.api-sports.io/football/players/396623.png" },
  { id: 111, name: "Hugo Ekitiké", club: "PSG", nationality: "France", position: "Forward", marketValue: 80, photo: "https://media.api-sports.io/football/players/174565.png" },
  { id: 113, name: "Ibrahima Konaté", club: "Liverpool", nationality: "France", position: "Defender", marketValue: 45, photo: "https://media.api-sports.io/football/players/1145.png" },
  { id: 115, name: "Kai Havertz", club: "Arsenal", nationality: "Germany", position: "Forward", marketValue: 55, photo: "https://media.api-sports.io/football/players/978.png" },
  { id: 116, name: "Gabriel Martinelli", club: "Arsenal", nationality: "Brazil", position: "Forward", marketValue: 45, photo: "https://media.api-sports.io/football/players/127769.png" },
  { id: 117, name: "Amad Diallo", club: "Manchester United", nationality: "Ivory Coast", position: "Forward", marketValue: 45, photo: "https://media.api-sports.io/football/players/157997.png" },
  { id: 118, name: "Christian Pulisic", club: "AC Milan", nationality: "USA", position: "Forward", marketValue: 40, photo: "https://media.api-sports.io/football/players/17.png" },
  { id: 119, name: "Ademola Lookman", club: "Atalanta", nationality: "Nigeria", position: "Forward", marketValue: 40, photo: "https://media.api-sports.io/football/players/18767.png" },
  { id: 120, name: "Evan Ndicka", club: "AS Roma", nationality: "France", position: "Defender", marketValue: 35, photo: "https://media.api-sports.io/football/players/1807.png" },
  { id: 121, name: "Dušan Vlahović", club: "Juventus", nationality: "Serbia", position: "Forward", marketValue: 35, photo: "https://media.api-sports.io/football/players/30415.png" },
  { id: 123, name: "Joshua Kimmich", club: "Bayern Munich", nationality: "Germany", position: "Midfielder", marketValue: 35, photo: "https://media.api-sports.io/football/players/502.png" },
  { id: 125, name: "Mohammed Kudus", club: "West Ham", nationality: "Ghana", position: "Forward", marketValue: 50, photo: "https://media.api-sports.io/football/players/15911.png" },
  { id: 126, name: "Noni Madueke", club: "Chelsea", nationality: "England", position: "Forward", marketValue: 50, photo: "https://media.api-sports.io/football/players/136723.png" },
  { id: 127, name: "Tijjani Reijnders", club: "AC Milan", nationality: "Netherlands", position: "Midfielder", marketValue: 50, photo: "https://media.api-sports.io/football/players/36902.png" },
  { id: 128, name: "Jonathan David", club: "Lille", nationality: "Canada", position: "Forward", marketValue: 30, photo: "https://media.api-sports.io/football/players/8489.png" },
  { id: 129, name: "Nuno Mendes", club: "PSG", nationality: "Portugal", position: "Defender", marketValue: 80, photo: "https://media.api-sports.io/football/players/263482.png" },
  { id: 130, name: "Désiré Doué", club: "PSG", nationality: "France", position: "Forward", marketValue: 120 },
  { id: 131, name: "Omar Marmoush", club: "Manchester City", nationality: "Egypt", position: "Forward", marketValue: 50 },
  { id: 132, name: "Frenkie de Jong", club: "Barcelona", nationality: "Netherlands", position: "Midfielder", marketValue: 35 },
  { id: 133, name: "Aleksandar Pavlovic", club: "Bayern Munich", nationality: "Germany", position: "Midfielder", marketValue: 90, photo: "https://media.api-sports.io/football/players/328033.png" },
  { id: 134, name: "Rayan Cherki", club: "Lyon", nationality: "France", position: "Forward", marketValue: 90, photo: "https://media.api-sports.io/football/players/156477.png" },
  { id: 135, name: "Rasmus Højlund", club: "Manchester United", nationality: "Denmark", position: "Forward", marketValue: 60 },
  { id: 136, name: "Pedro Neto", club: "Chelsea", nationality: "Portugal", position: "Forward", marketValue: 60 },
  { id: 137, name: "Cody Gakpo", club: "Liverpool", nationality: "Netherlands", position: "Forward", marketValue: 60, photo: "https://media.api-sports.io/football/players/247.png" },
  { id: 138, name: "Bryan Mbeumo", club: "Brentford", nationality: "Cameroon", position: "Forward", marketValue: 75, photo: "https://media.api-sports.io/football/players/20589.png" },
  { id: 139, name: "Eberechi Eze", club: "Crystal Palace", nationality: "England", position: "Forward", marketValue: 65 },
  { id: 140, name: "Matheus Cunha", club: "Wolves", nationality: "Brazil", position: "Forward", marketValue: 75 },
  { id: 141, name: "Adam Wharton", club: "Crystal Palace", nationality: "England", position: "Midfielder", marketValue: 70, photo: "https://media.api-sports.io/football/players/288102.png" },
  { id: 142, name: "Pablo Barrios", club: "Atlético Madrid", nationality: "Spain", position: "Midfielder", marketValue: 55, photo: "https://media.api-sports.io/football/players/336594.png" },
  { id: 143, name: "Nico Schlotterbeck", club: "Borussia Dortmund", nationality: "Germany", position: "Defender", marketValue: 55, photo: "https://media.api-sports.io/football/players/26243.png" },
  { id: 144, name: "Marc Cucurella", club: "Chelsea", nationality: "Spain", position: "Defender", marketValue: 50, photo: "https://media.api-sports.io/football/players/47380.png" },
  { id: 145, name: "Jeremie Frimpong", club: "Bayer Leverkusen", nationality: "Netherlands", position: "Defender", marketValue: 35, photo: "https://media.api-sports.io/football/players/152654.png" },
  { id: 146, name: "Crysencio Summerville", club: "West Ham", nationality: "Netherlands", position: "Forward", marketValue: 35 },
  { id: 147, name: "Curtis Jones", club: "Liverpool", nationality: "England", position: "Midfielder", marketValue: 35, photo: "https://media.api-sports.io/football/players/293.png" },
  { id: 148, name: "Joao Felix", club: "Chelsea", nationality: "Portugal", position: "Forward", marketValue: 28, photo: "https://media.api-sports.io/football/players/583.png" },
  { id: 149, name: "Endrick", club: "Real Madrid", nationality: "Brazil", position: "Forward", marketValue: 40 },
  { id: 150, name: "Goncalo Ramos", club: "PSG", nationality: "Portugal", position: "Forward", marketValue: 30, photo: "https://media.api-sports.io/football/players/738.png" },
  { id: 151, name: "Fabian Ruiz", club: "PSG", nationality: "Spain", position: "Midfielder", marketValue: 30, photo: "https://media.api-sports.io/football/players/328.png" },
  { id: 152, name: "David Raya", club: "Arsenal", nationality: "Spain", position: "Goalkeeper", marketValue: 30, photo: "https://media.api-sports.io/football/players/19465.png" },
];

// Get random players for games
export function getRandomPlayers(count: number, exclude: number[] = []): GamePlayer[] {
  const available = PLAYERS.filter((p) => !exclude.includes(p.id));
  const shuffled = [...available].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
